aliases:
- tf.config.experimental.get_visible_devices
- tf.compat.v1.config.experimental.get_visible_devices
- tf.compat.v1.config.get_visible_devices
constraints:
  device_type:
    default: None
    descp: (optional string) Only include devices matching this device type. For example
      "CPU" or "GPU".
    dtype:
    - tf.dtype
inputs:
  optional:
  - device_type
  required: []
link: https://www.tensorflow.org/versions/r2.3/api_docs/python/tf/config/get_visible_devices
outputs:
- List of visible PhysicalDevices
package: tensorflow
target: get_visible_devices
title: tf.config.get_visible_devices
version: 2.3.0
