aliases:
- tf.config.experimental.list_physical_devices
- tf.compat.v1.config.experimental.list_physical_devices
- tf.compat.v1.config.list_physical_devices
constraints:
  device_type:
    default: None
    descp: (optional string) Only include devices matching this device type. For example
      "CPU" or "GPU".
    dtype:
    - tf.dtype
inputs:
  optional:
  - device_type
  required: []
link: https://www.tensorflow.org/versions/r2.3/api_docs/python/tf/config/list_physical_devices
outputs:
- List of discovered tf.config.PhysicalDevice objects
package: tensorflow
target: list_physical_devices
title: tf.config.list_physical_devices
version: 2.3.0
