aliases:
- tf.compat.v1.config.run_functions_eagerly
constraints:
  run_eagerly:
    descp: Boolean. Whether to run functions eagerly.
    dtype:
    - tf.bool
    ndim:
    - '0'
inputs:
  optional: []
  required:
  - run_eagerly
link: https://www.tensorflow.org/versions/r2.3/api_docs/python/tf/config/run_functions_eagerly
package: tensorflow
target: run_functions_eagerly
title: tf.config.run_functions_eagerly
version: 2.3.0
