aliases:
- tf.compat.v1.config.experimental_connect_to_host
constraints:
  job_name:
    default: worker
    descp: The job name under which the new server will be accessible.
    normalized_default: DEFAULT DF_STR
    normalized_descp:
    - The job name under which the new server will be accessible
  remote_host:
    default: None
    descp: a single or a list the remote server addr in host-port format.
    normalized_default: DEFAULT None
    normalized_descp:
    - a single or a D_STRUCTURE the remote server addr in host port format
exceptions:
- ValueError: if remote_host is None.
inputs:
  optional:
  - remote_host
  - job_name
  required: []
link: https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/config/experimental_connect_to_host
package: tensorflow
target: experimental_connect_to_host
title: tf.config.experimental_connect_to_host
version: 2.1.0
