aliases:
- tf.compat.v1.config.experimental.set_memory_growth
constraints:
  device:
    descp: PhysicalDevice to configure
  enable:
    descp: (Boolean) Whether to enable or disable memory growth
exceptions:
- ValueError: Invalid PhysicalDevice specified.
- RuntimeError: Runtime is already initialized.
inputs:
  optional: []
  required:
  - device
  - enable
link: https://www.tensorflow.org/versions/r2.3/api_docs/python/tf/config/experimental/set_memory_growth
package: tensorflow
target: set_memory_growth
title: tf.config.experimental.set_memory_growth
version: 2.3.0
