aliases:
- tf.keras.applications.efficientnet.EfficientNetB7
- tf.compat.v1.keras.applications.EfficientNetB7
- tf.compat.v1.keras.applications.efficientnet.EfficientNetB7
constraints:
  '**kwargs':
    default: null
    descp: ''
  classes:
    default: '1000'
    descp: Optional number of classes to classify images into, only to be specified
      if include_top is True, and if no weights argument is specified. Defaults to
      1000 (number of ImageNet classes).
  classifier_activation:
    default: softmax
    descp: A str or callable. The activation function to use on the "top" layer. Ignored
      unless include_top=True. Set classifier_activation=None to return the logits
      of the "top" layer. Defaults to 'softmax'.
  include_top:
    default: 'True'
    descp: Whether to include the fully-connected layer at the top of the network.
      Defaults to True.
  input_shape:
    default: None
    descp: Optional shape tuple, only to be specified if include_top is False. It
      should have exactly 3 inputs channels.
  input_tensor:
    default: None
    descp: Optional Keras tensor (i.e. output of layers.Input()) to use as image input
      for the model.
  pooling:
    default: None
    descp: Optional pooling mode for feature extraction when include_top is False.
      Defaults to None. None means that the output of the model will be the 4D tensor
      output of the last convolutional layer. avg means that global average pooling
      will be applied to the output of the last convolutional layer, and thus the
      output of the model will be a 2D tensor. max means that global max pooling will
      be applied.
  weights:
    default: imagenet
    descp: One of None (random initialization), 'imagenet' (pre-training on ImageNet),
      or the path to the weights file to be loaded. Defaults to 'imagenet'.
inputs:
  optional:
  - include_top
  - weights
  - input_tensor
  - input_shape
  - pooling
  - classes
  - classifier_activation
  - '**kwargs'
  required: []
link: https://www.tensorflow.org/versions/r2.3/api_docs/python/tf/keras/applications/EfficientNetB7
outputs:
- A keras.Model instance.
package: tensorflow
target: EfficientNetB7
title: tf.keras.applications.EfficientNetB7
version: 2.3.0
