aliases:
- tf.compat.v1.keras.applications.vgg19.preprocess_input
constraints:
  data_format:
    default: None
    descp: Optional data format of the image tensor/array. Defaults to None, in which
      case the global setting tf.keras.backend.image_data_format() is used (unless
      you changed it, it defaults to "channels_last").
  x:
    descp: A floating point numpy.array or a tf.Tensor, 3D or 4D with 3 color channels,
      with values in the range [0, 255]. The preprocessed data are written over the
      input data if the data types are compatible. To avoid this behaviour, numpy.copy(x)
      can be used.
exceptions:
- ValueError: In case of unknown data_format argument.
inputs:
  optional:
  - data_format
  required:
  - x
link: https://www.tensorflow.org/versions/r2.3/api_docs/python/tf/keras/applications/vgg19/preprocess_input
outputs:
- Preprocessed numpy.array or a tf.Tensor with type float32. The images are converted
  from RGB to BGR, then each color channel is zero-centered with respect to the ImageNet
  dataset, without scaling.
package: tensorflow
target: preprocess_input
title: tf.keras.applications.vgg19.preprocess_input
version: 2.3.0
