aliases:
- tf.keras.applications.mobilenet.MobileNet
- tf.compat.v1.keras.applications.MobileNet
- tf.compat.v1.keras.applications.mobilenet.MobileNet
constraints:
  '**kwargs':
    default: null
    descp: For backwards compatibility only.
  alpha:
    default: '1.0'
    descp: Controls the width of the network. This is known as the width multiplier
      in the MobileNet paper. - If alpha < 1.0, proportionally decreases the number
      of filters in each layer. - If alpha > 1.0, proportionally increases the number
      of filters in each layer. - If alpha = 1, default number of filters from the
      paper are used at each layer. Default to 1.0.
  classes:
    default: '1000'
    descp: Optional number of classes to classify images into, only to be specified
      if include_top is True, and if no weights argument is specified. Defaults to
      1000.
  classifier_activation:
    default: softmax
    descp: A str or callable. The activation function to use on the "top" layer. Ignored
      unless include_top=True. Set classifier_activation=None to return the logits
      of the "top" layer.
  depth_multiplier:
    default: '1'
    descp: Depth multiplier for depthwise convolution. This is called the resolution
      multiplier in the MobileNet paper. Default to 1.0.
  dropout:
    default: '0.001'
    descp: Dropout rate. Default to 0.001.
  include_top:
    default: 'True'
    descp: Boolean, whether to include the fully-connected layer at the top of the
      network. Default to True.
  input_shape:
    default: None
    descp: Optional shape tuple, only to be specified if include_top is False (otherwise
      the input shape has to be (224, 224, 3) (with channels_last data format) or
      (3, 224, 224) (with channels_first data format). It should have exactly 3 inputs
      channels, and width and height should be no smaller than 32. E.g. (200, 200,
      3) would be one valid value. Default to None. input_shape will be ignored if
      the input_tensor is provided.
  input_tensor:
    default: None
    descp: Optional Keras tensor (i.e. output of layers.Input()) to use as image input
      for the model. input_tensor is useful for sharing inputs between multiple different
      networks. Default to None.
  pooling:
    default: None
    descp: Optional pooling mode for feature extraction when include_top is False.
      None (default) means that the output of the model will be the 4D tensor output
      of the last convolutional block. avg means that global average pooling will
      be applied to the output of the last convolutional block, and thus the output
      of the model will be a 2D tensor. max means that global max pooling will be
      applied.
  weights:
    default: imagenet
    descp: One of None (random initialization), 'imagenet' (pre-training on ImageNet),
      or the path to the weights file to be loaded. Default to imagenet.
exceptions:
- ValueError: in case of invalid argument for weights, or invalid input shape.
- ValueError: if classifier_activation is not softmax or None when using a pretrained
    top layer.
inputs:
  optional:
  - input_shape
  - alpha
  - depth_multiplier
  - dropout
  - include_top
  - weights
  - input_tensor
  - pooling
  - classes
  - classifier_activation
  - '**kwargs'
  required: []
link: https://www.tensorflow.org/versions/r2.2/api_docs/python/tf/keras/applications/MobileNet
outputs:
- A keras.Model instance.
package: tensorflow
target: MobileNet
title: tf.keras.applications.MobileNet
version: 2.2.0
