dtype:
    torch.qint8: torch.int8
    torch.qint16: torch.int16
    torch.qint32: torch.int32

    torch.quint8: torch.uint8
    torch.quint16: torch.uint16
    torch.quint32: torch.uint32

    uint8: torch.uint8
    torch.uint8: torch.uint8
    torch.bytetensor: torch.int8
    bytetensor: torch.int8
    torch.uint16: torch.uint16
    torch.uint32: torch.uint32

    int8: torch.int8
    torch.int8: torch.int8
    torch.chartensor: torch.int8
    int16: torch.int16
    torch.int16: torch.int16
    short: torch.int16
    torch.short: torch.int16
    torch.shorttensor: torch.int16
    int32: torch.int32
    torch.int32: torch.int32
    torch.int: torch.int32
    torch.inttensor: torch.int32
    int64: torch.int64
    torch.int64: torch.int64
    torch.long: torch.int64
    longtensor: torch.int64
    torch.longtensor: torch.int64
    int: int
    ints: int
    integer: int
    integers: int

    float16: torch.float16
    torch.float16: torch.float16
    half: torch.float16
    torch.half: torch.float16
    torch.halftensor: torch.float16
    float32: torch.float32
    torch.float32: torch.float32
    float: torch.float32
    floating: torch.float32
    torch.float: torch.float32
    torch.floattensor: torch.float32
    float64: torch.float64
    torch.float64: torch.float64
    double: torch.float64
    torch.double: torch.float64
    torch.doubletensor: torch.float64

    bool: torch.bool
    boolean: torch.bool
    torch.bool: torch.bool
    booltensor: torch.bool
    torch.booltensor: torch.bool

    str: string
    strings: string
    string: string
    

    torch.dtype: torch.dtype
    numeric: numeric

structure: 
    list: list
    lists: list
    array: list
    arrays: list
    tuple: tuple
    dict: dict
    dictionary: dict
    iterable: list
    sequence: list
    ndarray: list
    array_like: list
    vector: list
    vectors: list

tensor_t:
    tensor: torch.tensor
    tensors: torch.tensor
    sparsetensor: SparseTensor
    torch.tensor: torch.tensor