constraints:
  assume_finite: {default: None, descp: 'bool, optional If True, validation for finiteness
      will be skipped, saving time, but leading to potential crashes. If False, validation
      for finiteness will be performed, avoiding error.  Global default: False.'}
  print_changed_only: {default: None, descp: 'bool, optional If True, only the parameters
      that were set to non-default values will be printed when printing an estimator.
      For example, ``print(SVC())`` while True will only print ''SVC()'' while the
      default behaviour would be to print ''SVC(C=1.0, cache_size=200, ...)'' with
      all the non-changed parameters.'}
  working_memory: {default: None, descp: 'int, optional If set, scikit-learn will
      attempt to limit the size of temporary arrays to this number of MiB (per job
      when parallelised), often saving both computation time and memory on expensive
      operations that can be performed in chunks. Global default: 1024.'}
inputs:
  optional: [assume_finite, working_memory, print_changed_only]
  required: []
link: ''
package: sklearn
target: set_config
title: sklearn.set_config
version: 0.24.2
