constraints:
  batch_size: {descp: ''}
  min_batch_size: {default: '0', descp: ''}
  n: {descp: 'int batch_size : int Number of element in each batch min_batch_size
      : int, default=0 Minimum batch size to produce.'}
inputs:
  optional: [min_batch_size]
  required: [n, batch_size]
link: ''
package: sklearn
target: gen_batches
title: sklearn.utils.gen_batches
version: 0.24.2
