aliases:
- tf.config.experimental.set_virtual_device_configuration
- tf.compat.v1.config.experimental.set_virtual_device_configuration
- tf.compat.v1.config.set_logical_device_configuration
constraints:
  device:
    descp: The `PhysicalDevice` to configure.
    dtype:
    - int
    - tf.bool
    - tf.dtype
    - tf.string
    enum:
    - PhysicalDevice
    ndim:
    - '0'
    - '1'
    range:
    - '[0,inf)'
  logical_devices:
    descp: (optional) List of `tf.config.LogicalDeviceConfiguration`objects to allocate
      for the specified `PhysicalDevice`. If None, the default configuration will
      be used.
    dtype:
    - int
    - numeric
    - tf.bool
    - tf.dtype
    - tf.string
    ndim:
    - '0'
    - '1'
    - objects_to_allocate_for_the_specified
    range:
    - '[0,inf)'
    shape:
    - '[1]'
    - '[n]'
    structure:
    - list
exceptions:
- ValueError: If argument validation fails.
- RuntimeError: Runtime is already initialized.
inputs:
  optional: []
  required:
  - device
  - logical_devices
link: https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/config/set_logical_device_configuration
package: tensorflow
target: set_logical_device_configuration
title: tf.config.set_logical_device_configuration
version: 2.1.0
